Bootstrapper
Mapc1/ESR22-23 pull request #1
Opened 2022-11-03 12:30 UTC by Mapc1

Bootstrapper simples. Recebe uma mensagem e responde com o ficheiro.

2022-11-03 12:34 UTC, DBarbosa15987 approved these changes
Ta bom

2022-11-07 20:36 UTC, gonaloppcc commented on src/apps/bootstrapper.rs
> +    stream.write(file.as_bytes()).unwrap();
Temos que estar sempre a fazer unwrap??? O código não fica tão legivel

2022-11-07 20:36 UTC, gonaloppcc commented on src/apps/bootstrapper.rs
> +    let listener = TcpListener::bind("0.0.0.0:8080")
Isto não devia estar hardcoded

2022-11-07 20:38 UTC, gonaloppcc requested changes
[Issue](https://github.com/Mapc1/esr22-23/pull/1/files#r1015874715)

2022-11-20 22:53 UTC, gonaloppcc approved these changes

2022-11-21 01:18 UTC, merged